# need to change data set
attach(googleplay_2way)

# Time tests
time_tests = list()

time_tests["aliasflowins"] <- list(wilcox.test(time~X..aliasflowins))
time_tests["taintwrapper"] <- list(wilcox.test(time~X..taintwrapper))
time_tests["nocallbacks"] <- list(wilcox.test(time~X..nocallbacks))
time_tests["nothischainreduction"] <- list(wilcox.test(time~X..nothischainreduction))
time_tests["onesourceatatime"] <- list(wilcox.test(time~X..onesourceatatime))
time_tests["onecomponentatatime"] <- list(wilcox.test(time~X..onecomponentatatime))
time_tests["pathspecificresults"] <- list(wilcox.test(time~X..pathspecificresults))
time_tests["enablereflection"] <- list(wilcox.test(time~X..enablereflection))
time_tests["singlejoinpointabstraction"] <- list(wilcox.test(time~X..singlejoinpointabstraction))
time_tests["aliasalgo"] <- list(kruskal.test(time~X..aliasalgo))
time_tests["aplength"] <- list(kruskal.test(time~X..aplength))
time_tests["callbackanalyzer"] <- list(kruskal.test(time~X..callbackanalyzer))
time_tests["codeelimination"] <- list(kruskal.test(time~X..codeelimination))
time_tests["cgalgo"] <- list(kruskal.test(time~X..cgalgo))
time_tests["dataflowsolver"] <- list(kruskal.test(time~X..dataflowsolver))
time_tests["implicit"] <- list(kruskal.test(time~X..implicit))
time_tests["maxcallbackspercomponent"] <- list(kruskal.test(time~X..maxcallbackspercomponent))
time_tests["maxcallbacksdepth"] <- list(kruskal.test(time~X..maxcallbacksdepth))
time_tests["pathalgo"] <- list(kruskal.test(time~X..pathalgo))
time_tests["staticmode"] <- list(kruskal.test(time~X..staticmode))
time_tests <- time_tests[order(sapply(time_tests, "[[", "p.value"))]
# Num_Flows tests
num_flows_tests = list()

num_flows_tests["aliasflowins"] <- list(wilcox.test(num_flows~X..aliasflowins))
num_flows_tests["taintwrapper"] <- list(wilcox.test(num_flows~X..taintwrapper))
num_flows_tests["nocallbacks"] <- list(wilcox.test(num_flows~X..nocallbacks))
num_flows_tests["nothischainreduction"] <- list(wilcox.test(num_flows~X..nothischainreduction))
num_flows_tests["onesourceatatime"] <- list(wilcox.test(num_flows~X..onesourceatatime))
num_flows_tests["onecomponentatatime"] <- list(wilcox.test(num_flows~X..onecomponentatatime))
num_flows_tests["pathspecificresults"] <- list(wilcox.test(num_flows~X..pathspecificresults))
num_flows_tests["enablereflection"] <- list(wilcox.test(num_flows~X..enablereflection))
num_flows_tests["singlejoinpointabstraction"] <- list(wilcox.test(num_flows~X..singlejoinpointabstraction))
num_flows_tests["aliasalgo"] <- list(kruskal.test(num_flows~X..aliasalgo))
num_flows_tests["aplength"] <- list(kruskal.test(num_flows~X..aplength))
num_flows_tests["callbackanalyzer"] <- list(kruskal.test(num_flows~X..callbackanalyzer))
num_flows_tests["codeelimination"] <- list(kruskal.test(num_flows~X..codeelimination))
num_flows_tests["cgalgo"] <- list(kruskal.test(num_flows~X..cgalgo))
num_flows_tests["dataflowsolver"] <- list(kruskal.test(num_flows~X..dataflowsolver))
num_flows_tests["implicit"] <- list(kruskal.test(num_flows~X..implicit))
num_flows_tests["maxcallbackspercomponent"] <- list(kruskal.test(num_flows~X..maxcallbackspercomponent))
num_flows_tests["maxcallbacksdepth"] <- list(kruskal.test(num_flows~X..maxcallbacksdepth))
num_flows_tests["pathalgo"] <- list(kruskal.test(num_flows~X..pathalgo))
num_flows_tests["staticmode"] <- list(kruskal.test(num_flows~X..staticmode))
num_flows_tests <- num_flows_tests[order(sapply(num_flows_tests, "[[", "p.value"))]